# Generated by Django 5.1.3 on 2024-11-23 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "letter_header",
                    models.CharField(
                        help_text="Укажите тему письма",
                        max_length=100,
                        verbose_name="Тема письма",
                    ),
                ),
                (
                    "letter_text",
                    models.TextField(
                        help_text="Укажите содержание письма",
                        verbose_name="Текст письма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["letter_header", "letter_text"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите Email получателя",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Введите ФИО получателя",
                        max_length=100,
                        verbose_name="ФИО получателя рассылки",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Укажите комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылок",
                "verbose_name_plural": "Получатели рассылок",
                "ordering": ["email", "full_name", "comment"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("launched", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        max_length=15,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "massage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите тему сообщения",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletters",
                        to="mailings.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Укажите получателей",
                        related_name="newsletters",
                        to="mailings.recipient",
                        verbose_name="Получатели",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["created_at", "updated_at", "status", "massage"],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("successful", "Успешно"),
                            ("not successful", "Не успешно"),
                        ],
                        max_length=15,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "mail_server_response",
                    models.TextField(verbose_name="Ответ почтового сервера"),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mailing_attempts",
                        to="mailings.newsletter",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "ordering": [
                    "created_at",
                    "status",
                    "mail_server_response",
                    "newsletter",
                ],
            },
        ),
    ]
