# Generated by Django 5.1.3 on 2024-11-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["letter_header", "letter_text", "owner"],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["created_at", "updated_at", "status", "massage", "owner"],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["email", "full_name", "comment", "owner"],
                "verbose_name": "Получатель рассылок",
                "verbose_name_plural": "Получатели рассылок",
            },
        ),
    ]
