# Generated by Django 5.1.3 on 2024-12-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_message_owner_newsletter_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["created_at", "updated_at", "status", "massage", "owner"],
                "permissions": [("disabling_mailings", "disabling mailings")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
